"""
seed_test_contact.py - Inserta un contacto de prueba en DynamoDB.

Util para:
- Validar el pipeline contacts -> Stream -> stream_processor -> Neon
- Generar data para QA del dashboard sin tener que pasar por el form
- Smoke tests post-deploy

Uso:
    AWS_PROFILE=tfs-dev python scripts/seed_test_contact.py --stage dev
    AWS_PROFILE=tfs-dev python scripts/seed_test_contact.py --stage prod --name "Real Lead"

Reglas:
- NUNCA correr contra prod salvo que el lead sea legitimo
- El contacto inserta directo a DynamoDB (bypass Lambda + Turnstile)
- TTL automatico 60 dias (mismo que en produccion)
"""

import argparse
import sys
import time
from datetime import UTC, datetime, timedelta

import boto3
from botocore.exceptions import ClientError


def make_item(name: str, email: str, message: str, niche: str) -> dict:
    """Construye el item DynamoDB con el shape canonico de contacts."""
    now = datetime.now(UTC)
    ttl = int((now + timedelta(days=60)).timestamp())
    contact_id = f'seed-{int(time.time())}-{niche}'

    return {
        'pk': {'S': f'CONTACT#{contact_id}'},
        'sk': {'S': '#META'},
        'id': {'S': contact_id},
        'created_at': {'S': now.isoformat()},
        'name': {'S': name},
        'email': {'S': email},
        'niche': {'S': niche},
        'message': {'S': message},
        'status': {'S': 'new'},
        'source': {'S': 'seed_script'},
        'ttl': {'N': str(ttl)},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--stage',
        choices=['dev', 'prod'],
        default='dev',
        help='Stage del stack (dev|prod)',
    )
    parser.add_argument(
        '--name',
        default='Smoke Test',
        help='Nombre del contacto (default: "Smoke Test")',
    )
    parser.add_argument(
        '--email',
        default='smoke@example.com',
        help='Email del contacto',
    )
    parser.add_argument(
        '--message',
        default='Auto-generated by seed_test_contact.py - ignore',
        help='Mensaje del contacto',
    )
    parser.add_argument(
        '--niche',
        default='generic',
        choices=['generic', 'hub', 'fintech', 'architect', 'leader', 'vibe'],
        help='Niche del lead',
    )
    parser.add_argument(
        '--region',
        default='us-east-1',
        help='Region AWS (default us-east-1)',
    )
    args = parser.parse_args()

    if args.stage == 'prod' and args.email == 'smoke@example.com':
        print('ERROR: No insertar contactos de prueba en prod.')
        print('Pasa --email real si es un lead legitimo.')
        return 1

    table_name = f'portfolio-contacts-{args.stage}'
    client = boto3.client('dynamodb', region_name=args.region)

    item = make_item(args.name, args.email, args.message, args.niche)

    try:
        client.put_item(TableName=table_name, Item=item)
    except ClientError as exc:
        print(f'ERROR insertando en {table_name}: {exc}')
        return 2

    print(f'Insertado contacto {item["id"]["S"]} en {table_name}')
    print('Stream debera replicarlo a Neon en ~2-5 segundos.')
    print('Verificar:')
    print(f'  psql $NEON_URL -c "SELECT id, email, niche FROM portfolio.contacts WHERE id = \'{item["id"]["S"]}\';"')
    return 0


if __name__ == '__main__':
    sys.exit(main())
