"""init unified schema

Revision ID: 81c2cc51db34
Revises:
Create Date: 2026-05-19 06:33:44.026015
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c2cc51db34'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Piezas que Alembic no autogenera (extension, particion, trigger, seed).
# Viven en alembic/_init_schema_extras.py — el `prepend_sys_path` del
# alembic.ini incluye el directorio del proyecto; alembic/ esta en el path
# via la carga del propio script de migracion.
import _init_schema_extras as extras  # noqa: E402


def upgrade() -> None:
    # La extension citext debe existir ANTES de crear `contacts` (su columna
    # `email` es CITEXT). Alembic no autogenera CREATE EXTENSION.
    op.execute(extras.create_citext_extension())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('awarded_ym', sa.String(length=7), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("awarded_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name=op.f('ck_awards_awarded_ym_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards')),
    sa.UniqueConstraint('slug', name=op.f('uq_awards_slug'))
    )
    op.create_table('certificates',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('slug', name=op.f('uq_certificates_slug'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stream_event_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Text(), nullable=True),
    sa.Column('budget', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('country', sa.CHAR(length=2), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.CheckConstraint("service_type IS NULL OR service_type IN ('consulting', 'fulltime', 'contract', 'other')", name=op.f('ck_contacts_service_type_valid')),
    sa.CheckConstraint("status IN ('new', 'contacted', 'qualified', 'converted', 'rejected')", name=op.f('ck_contacts_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('stream_event_id', name=op.f('uq_contacts_stream_event_id'))
    )
    op.create_index('idx_contacts_created_at', 'contacts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contacts_message_fts', 'contacts', [sa.literal_column("to_tsvector('spanish', message)")], unique=False, postgresql_using='gin')
    op.create_index('idx_contacts_niche_created', 'contacts', ['niche', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_contacts_session_id', 'contacts', ['session_id'], unique=False, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('idx_contacts_status', 'contacts', ['status'], unique=False, postgresql_where=sa.text("status IN ('new', 'contacted')"))
    op.create_table('education',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.String(length=16), nullable=False),
    sa.Column('end_year', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education')),
    sa.UniqueConstraint('slug', name=op.f('uq_education_slug'))
    )
    op.create_table('event_types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_types')),
    sa.UniqueConstraint('code_name', name=op.f('uq_event_types_code_name'))
    )
    op.create_table('experiences',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('company_url', sa.String(length=500), nullable=True),
    sa.Column('start_ym', sa.String(length=7), nullable=False),
    sa.Column('end_ym', sa.String(length=7), nullable=True),
    sa.Column('seniority', sa.Enum('intern', 'junior', 'mid', 'senior', 'lead', name='seniority'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("end_ym IS NULL OR end_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name=op.f('ck_experiences_end_ym_format')),
    sa.CheckConstraint("start_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name=op.f('ck_experiences_start_ym_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences')),
    sa.UniqueConstraint('slug', name=op.f('uq_experiences_slug')),
    comment='Experiencias laborales del CV'
    )
    op.create_table('languages',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('slug', name=op.f('uq_languages_slug'))
    )
    op.create_table('niches',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niches')),
    sa.UniqueConstraint('slug', name=op.f('uq_niches_slug'))
    )
    op.create_table('processed_stream_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_processed_stream_events'))
    )
    op.create_table('profile',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('handle', name=op.f('uq_profile_handle'))
    )
    op.create_table('projects',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('repo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'concept', name='project_status'), nullable=False),
    sa.Column('project_type', sa.Enum('web', 'mobile', 'cli', 'library', 'ai', 'fintech-platform', name='project_type'), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', name=op.f('uq_projects_slug'))
    )
    op.create_table('publications',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
    sa.UniqueConstraint('slug', name=op.f('uq_publications_slug'))
    )
    op.create_table('references',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_references')),
    sa.UniqueConstraint('slug', name=op.f('uq_references_slug'))
    )
    op.create_table('skill_categories',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('technical', 'soft', name='skill_kind'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_skill_categories_slug'))
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_table('tech_tags',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tech_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tech_tags_name'))
    )
    op.create_table('translations',
    sa.Column('entity_type', sa.Enum('profile', 'experience', 'experience_bullet', 'project', 'project_case_study', 'project_metric', 'skill_category', 'certificate', 'award', 'education', 'reference', 'language', 'publication', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.Enum('es', 'en', name='locale'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'field', 'locale', name=op.f('pk_translations')),
    comment='Textos bilingues del CV. entity_id es polimorfico — su integridad la valida el trigger assert_entity_exists.'
    )
    op.create_table('award_niches',
    sa.Column('award_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_award_niches_award_id_awards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_award_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('award_id', 'niche_id', name=op.f('pk_award_niches'))
    )
    op.create_table('certificate_niches',
    sa.Column('certificate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_certificate_niches_certificate_id_certificates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_certificate_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificate_id', 'niche_id', name=op.f('pk_certificate_niches'))
    )
    op.create_table('education_niches',
    sa.Column('education_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], name=op.f('fk_education_niches_education_id_education'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_education_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('education_id', 'niche_id', name=op.f('pk_education_niches'))
    )
    op.create_table('experience_bullets',
    sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.Enum('responsibility', 'achievement', name='bullet_kind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_experience_bullets_experience_id_experiences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_bullets')),
    sa.UniqueConstraint('experience_id', 'kind', 'position', name='experience_bullet')
    )
    op.create_table('experience_niches',
    sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_experience_niches_experience_id_experiences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_experience_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'niche_id', name=op.f('pk_experience_niches'))
    )
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.Enum('technical', 'soft', name='skill_kind'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_experience_skills_experience_id_experiences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_experience_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id', 'kind', name=op.f('pk_experience_skills'))
    )
    op.create_table('language_niches',
    sa.Column('language_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_niches_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_language_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'niche_id', name=op.f('pk_language_niches'))
    )
    op.create_table('niche_priorities',
    sa.Column('entity_type', sa.Enum('profile', 'experience', 'experience_bullet', 'project', 'project_case_study', 'project_metric', 'skill_category', 'certificate', 'award', 'education', 'reference', 'language', 'publication', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_niche_priorities_niche_id_niches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'niche_id', name=op.f('pk_niche_priorities')),
    comment='Priority por (entidad, niche). entity_id es polimorfico — integridad via trigger assert_entity_exists.'
    )
    op.create_table('profile_stats',
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('companies', sa.Integer(), nullable=False),
    sa.Column('countries', sa.Integer(), nullable=False),
    sa.Column('certifications', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_profile_stats_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_stats')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_profile_stats_profile_id'))
    )
    op.create_table('project_case_studies',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_case_studies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_case_studies')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_case_studies_project_id'))
    )
    op.create_table('project_metrics',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric_key', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_metrics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_metrics')),
    sa.UniqueConstraint('project_id', 'metric_key', name='project_metric')
    )
    op.create_table('project_niches',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_project_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_niches_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'niche_id', name=op.f('pk_project_niches'))
    )
    op.create_table('project_tech_tags',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tech_tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tech_tags_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_tag_id'], ['tech_tags.id'], name=op.f('fk_project_tech_tags_tech_tag_id_tech_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tech_tag_id', name=op.f('pk_project_tech_tags'))
    )
    op.create_table('publication_niches',
    sa.Column('publication_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_publication_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_publication_niches_publication_id_publications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'niche_id', name=op.f('pk_publication_niches'))
    )
    op.create_table('reference_niches',
    sa.Column('reference_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_reference_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], name=op.f('fk_reference_niches_reference_id_references'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reference_id', 'niche_id', name=op.f('pk_reference_niches'))
    )
    op.create_table('skill_category_niches',
    sa.Column('skill_category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_skill_category_niches_niche_id_niches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_category_id'], ['skill_categories.id'], name=op.f('fk_skill_category_niches_skill_category_id_skill_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_category_id', 'niche_id', name=op.f('pk_skill_category_niches'))
    )
    op.create_table('skill_category_skills',
    sa.Column('skill_category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_category_id'], ['skill_categories.id'], name=op.f('fk_skill_category_skills_skill_category_id_skill_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_category_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_category_id', 'skill_id', name=op.f('pk_skill_category_skills'))
    )
    op.create_table('tracking_events',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('page_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stream_event_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('page_path', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.Text(), nullable=True),
    sa.Column('utm_medium', sa.Text(), nullable=True),
    sa.Column('utm_campaign', sa.Text(), nullable=True),
    sa.Column('utm_content', sa.Text(), nullable=True),
    sa.Column('utm_term', sa.Text(), nullable=True),
    sa.Column('viewport_width', sa.Integer(), nullable=True),
    sa.Column('viewport_height', sa.Integer(), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('country', sa.CHAR(length=2), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.Text(), nullable=True),
    sa.Column('browser_version', sa.Text(), nullable=True),
    sa.Column('os', sa.Text(), nullable=True),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_tracking_events_event_type_id_event_types')),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_tracking_country', 'tracking_events', ['country'], unique=False, postgresql_where=sa.text('country IS NOT NULL'))
    op.create_index('idx_tracking_created_brin', 'tracking_events', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_tracking_device_type', 'tracking_events', ['device_type'], unique=False)
    op.create_index('idx_tracking_event_type', 'tracking_events', ['event_type_id'], unique=False)
    op.create_index('idx_tracking_niche_created', 'tracking_events', ['niche', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('niche IS NOT NULL'))
    op.create_index('idx_tracking_page_path', 'tracking_events', ['page_path'], unique=False)
    op.create_index('idx_tracking_referrer', 'tracking_events', ['referrer'], unique=False, postgresql_where=sa.text('referrer IS NOT NULL'))
    op.create_index('idx_tracking_session_created', 'tracking_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_tracking_utm_source', 'tracking_events', ['utm_source'], unique=False, postgresql_where=sa.text('utm_source IS NOT NULL'))
    # ### end Alembic commands ###

    # --- Ajustes manuales (Alembic no los autogenera) -----------------------

    # 1. Particion default de tracking_events. Sin ella, un INSERT cuya
    #    `created_at` no cae en ninguna particion explicita falla.
    op.execute(extras.create_partition_default())

    # 2. Trigger de integridad polimorfica de translations / niche_priorities.
    op.execute(extras.entity_trigger_fn_sql)
    for _t in extras.entity_trigger_tables:
        op.execute(
            f'CREATE TRIGGER trg_{_t}_entity_exists '
            f'BEFORE INSERT OR UPDATE ON {_t} '
            f'FOR EACH ROW EXECUTE FUNCTION assert_entity_exists()'
        )

    # 3. Seed del catalogo event_types (16 tipos, UUIDv7 literales).
    op.bulk_insert(
        sa.table(
            'event_types',
            sa.column('id', postgresql.UUID()),
            sa.column('code_name', sa.Text()),
            sa.column('description', sa.Text()),
        ),
        extras.event_types_seed,
    )


def downgrade() -> None:
    # Ajustes manuales primero (orden inverso): triggers + funcion antes de
    # dropear las tablas que los usan.
    for _t in extras.entity_trigger_tables:
        op.execute(
            f'DROP TRIGGER IF EXISTS trg_{_t}_entity_exists ON {_t}'
        )
    op.execute('DROP FUNCTION IF EXISTS assert_entity_exists()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracking_utm_source', table_name='tracking_events', postgresql_where=sa.text('utm_source IS NOT NULL'))
    op.drop_index('idx_tracking_session_created', table_name='tracking_events')
    op.drop_index('idx_tracking_referrer', table_name='tracking_events', postgresql_where=sa.text('referrer IS NOT NULL'))
    op.drop_index('idx_tracking_page_path', table_name='tracking_events')
    op.drop_index('idx_tracking_niche_created', table_name='tracking_events', postgresql_where=sa.text('niche IS NOT NULL'))
    op.drop_index('idx_tracking_event_type', table_name='tracking_events')
    op.drop_index('idx_tracking_device_type', table_name='tracking_events')
    op.drop_index('idx_tracking_created_brin', table_name='tracking_events', postgresql_using='brin')
    op.drop_index('idx_tracking_country', table_name='tracking_events', postgresql_where=sa.text('country IS NOT NULL'))
    op.drop_table('tracking_events')
    op.drop_table('skill_category_skills')
    op.drop_table('skill_category_niches')
    op.drop_table('reference_niches')
    op.drop_table('publication_niches')
    op.drop_table('project_tech_tags')
    op.drop_table('project_niches')
    op.drop_table('project_metrics')
    op.drop_table('project_case_studies')
    op.drop_table('profile_stats')
    op.drop_table('niche_priorities')
    op.drop_table('language_niches')
    op.drop_table('experience_skills')
    op.drop_table('experience_niches')
    op.drop_table('experience_bullets')
    op.drop_table('education_niches')
    op.drop_table('certificate_niches')
    op.drop_table('award_niches')
    op.drop_table('translations')
    op.drop_table('tech_tags')
    op.drop_table('skills')
    op.drop_table('skill_categories')
    op.drop_table('references')
    op.drop_table('publications')
    op.drop_table('projects')
    op.drop_table('profile')
    op.drop_table('processed_stream_events')
    op.drop_table('niches')
    op.drop_table('languages')
    op.drop_table('experiences')
    op.drop_table('event_types')
    op.drop_table('education')
    op.drop_index('idx_contacts_status', table_name='contacts', postgresql_where=sa.text("status IN ('new', 'contacted')"))
    op.drop_index('idx_contacts_session_id', table_name='contacts', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index('idx_contacts_niche_created', table_name='contacts')
    op.drop_index('idx_contacts_message_fts', table_name='contacts', postgresql_using='gin')
    op.drop_index('idx_contacts_email', table_name='contacts')
    op.drop_index('idx_contacts_created_at', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('certificates')
    op.drop_table('awards')
    # ### end Alembic commands ###
    # Los tipos ENUM nativos NO se borran con DROP TABLE — Alembic no los
    # autogenera en el downgrade. Sin esto, un re-upgrade falla con
    # "type already exists". citext NO se borra (otros schemas la usan).
    for _enum in extras.enum_type_names:
        op.execute(f'DROP TYPE IF EXISTS {_enum}')
