"""init cv schema

Revision ID: b79eba6beb00
Revises:
Create Date: 2026-05-18 20:11:20.313255
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b79eba6beb00'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'awards',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('issuer', sa.String(length=200), nullable=False),
        sa.Column('awarded_ym', sa.String(length=7), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "awarded_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name=op.f('ck_awards_awarded_ym_format'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_awards')),
        sa.UniqueConstraint('slug', name=op.f('uq_awards_slug')),
    )
    op.create_table(
        'certificates',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('issuer', sa.String(length=200), nullable=False),
        sa.Column('issued_on', sa.Date(), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
        sa.UniqueConstraint('slug', name=op.f('uq_certificates_slug')),
    )
    op.create_table(
        'education',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('institution', sa.String(length=200), nullable=False),
        sa.Column('start_year', sa.String(length=16), nullable=False),
        sa.Column('end_year', sa.String(length=16), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_education')),
        sa.UniqueConstraint('slug', name=op.f('uq_education_slug')),
    )
    op.create_table(
        'experiences',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('company', sa.String(length=160), nullable=False),
        sa.Column('company_url', sa.String(length=500), nullable=True),
        sa.Column('start_ym', sa.String(length=7), nullable=False),
        sa.Column('end_ym', sa.String(length=7), nullable=True),
        sa.Column(
            'seniority',
            sa.Enum(
                'intern', 'junior', 'mid', 'senior', 'lead', name='seniority'
            ),
            nullable=False,
        ),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_ym IS NULL OR end_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name=op.f('ck_experiences_end_ym_format'),
        ),
        sa.CheckConstraint(
            "start_ym ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name=op.f('ck_experiences_start_ym_format'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences')),
        sa.UniqueConstraint('slug', name=op.f('uq_experiences_slug')),
        comment='Experiencias laborales del CV',
    )
    op.create_table(
        'languages',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
        sa.UniqueConstraint('slug', name=op.f('uq_languages_slug')),
    )
    op.create_table(
        'niches',
        sa.Column('slug', sa.String(length=32), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_niches')),
        sa.UniqueConstraint('slug', name=op.f('uq_niches_slug')),
    )
    op.create_table(
        'profile',
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('handle', sa.String(length=80), nullable=False),
        sa.Column('location', sa.String(length=160), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('phone', sa.String(length=40), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=False),
        sa.Column('github_url', sa.String(length=500), nullable=False),
        sa.Column('website_url', sa.String(length=500), nullable=True),
        sa.Column('avatar_url', sa.String(length=500), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
        sa.UniqueConstraint('handle', name=op.f('uq_profile_handle')),
    )
    op.create_table(
        'projects',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('repo', sa.String(length=500), nullable=True),
        sa.Column(
            'status',
            sa.Enum('active', 'inactive', 'concept', name='project_status'),
            nullable=False,
        ),
        sa.Column(
            'project_type',
            sa.Enum(
                'web',
                'mobile',
                'cli',
                'library',
                'ai',
                'fintech-platform',
                name='project_type',
            ),
            nullable=False,
        ),
        sa.Column('is_confidential', sa.Boolean(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
        sa.UniqueConstraint('slug', name=op.f('uq_projects_slug')),
    )
    op.create_table(
        'publications',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('platform', sa.String(length=120), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('canonical_url', sa.String(length=500), nullable=True),
        sa.Column('published_on', sa.Date(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
        sa.UniqueConstraint('slug', name=op.f('uq_publications_slug')),
    )
    op.create_table(
        'references',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('role', sa.String(length=200), nullable=False),
        sa.Column('company', sa.String(length=200), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_references')),
        sa.UniqueConstraint('slug', name=op.f('uq_references_slug')),
    )
    op.create_table(
        'skill_categories',
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('technical', 'soft', name='skill_kind'),
            nullable=False,
        ),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories')),
        sa.UniqueConstraint('slug', name=op.f('uq_skill_categories_slug')),
    )
    op.create_table(
        'skills',
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
        sa.UniqueConstraint('name', name=op.f('uq_skills_name')),
    )
    op.create_table(
        'tech_tags',
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tech_tags')),
        sa.UniqueConstraint('name', name=op.f('uq_tech_tags_name')),
    )
    op.create_table(
        'translations',
        sa.Column(
            'entity_type',
            sa.Enum(
                'profile',
                'experience',
                'experience_bullet',
                'project',
                'project_case_study',
                'project_metric',
                'skill_category',
                'certificate',
                'award',
                'education',
                'reference',
                'language',
                'publication',
                name='entity_type',
            ),
            nullable=False,
        ),
        sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('field', sa.String(length=64), nullable=False),
        sa.Column('locale', sa.Enum('es', 'en', name='locale'), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            'entity_type',
            'entity_id',
            'field',
            'locale',
            name=op.f('pk_translations'),
        ),
        comment='Textos bilingues del CV. entity_id es polimorfico — su integridad la valida el trigger assert_entity_exists.',
    )
    op.create_table(
        'award_niches',
        sa.Column('award_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['award_id'],
            ['awards.id'],
            name=op.f('fk_award_niches_award_id_awards'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_award_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'award_id', 'niche_id', name=op.f('pk_award_niches')
        ),
    )
    op.create_table(
        'certificate_niches',
        sa.Column('certificate_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['certificate_id'],
            ['certificates.id'],
            name=op.f('fk_certificate_niches_certificate_id_certificates'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_certificate_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'certificate_id', 'niche_id', name=op.f('pk_certificate_niches')
        ),
    )
    op.create_table(
        'education_niches',
        sa.Column('education_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['education_id'],
            ['education.id'],
            name=op.f('fk_education_niches_education_id_education'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_education_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'education_id', 'niche_id', name=op.f('pk_education_niches')
        ),
    )
    op.create_table(
        'experience_bullets',
        sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('responsibility', 'achievement', name='bullet_kind'),
            nullable=False,
        ),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['experience_id'],
            ['experiences.id'],
            name=op.f('fk_experience_bullets_experience_id_experiences'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_bullets')),
        sa.UniqueConstraint(
            'experience_id', 'kind', 'position', name='experience_bullet'
        ),
    )
    op.create_table(
        'experience_niches',
        sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['experience_id'],
            ['experiences.id'],
            name=op.f('fk_experience_niches_experience_id_experiences'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_experience_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'experience_id', 'niche_id', name=op.f('pk_experience_niches')
        ),
    )
    op.create_table(
        'experience_skills',
        sa.Column('experience_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('technical', 'soft', name='skill_kind'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['experience_id'],
            ['experiences.id'],
            name=op.f('fk_experience_skills_experience_id_experiences'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skills.id'],
            name=op.f('fk_experience_skills_skill_id_skills'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'experience_id',
            'skill_id',
            'kind',
            name=op.f('pk_experience_skills'),
        ),
    )
    op.create_table(
        'language_niches',
        sa.Column('language_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['language_id'],
            ['languages.id'],
            name=op.f('fk_language_niches_language_id_languages'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_language_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'language_id', 'niche_id', name=op.f('pk_language_niches')
        ),
    )
    op.create_table(
        'niche_priorities',
        sa.Column(
            'entity_type',
            sa.Enum(
                'profile',
                'experience',
                'experience_bullet',
                'project',
                'project_case_study',
                'project_metric',
                'skill_category',
                'certificate',
                'award',
                'education',
                'reference',
                'language',
                'publication',
                name='entity_type',
            ),
            nullable=False,
        ),
        sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_niche_priorities_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'entity_type',
            'entity_id',
            'niche_id',
            name=op.f('pk_niche_priorities'),
        ),
        comment='Priority por (entidad, niche). entity_id es polimorfico — integridad via trigger assert_entity_exists.',
    )
    op.create_table(
        'profile_stats',
        sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('years_experience', sa.Integer(), nullable=False),
        sa.Column('companies', sa.Integer(), nullable=False),
        sa.Column('countries', sa.Integer(), nullable=False),
        sa.Column('certifications', sa.Integer(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['profile_id'],
            ['profile.id'],
            name=op.f('fk_profile_stats_profile_id_profile'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_stats')),
        sa.UniqueConstraint(
            'profile_id', name=op.f('uq_profile_stats_profile_id')
        ),
    )
    op.create_table(
        'project_case_studies',
        sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
            name=op.f('fk_project_case_studies_project_id_projects'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_project_case_studies')),
        sa.UniqueConstraint(
            'project_id', name=op.f('uq_project_case_studies_project_id')
        ),
    )
    op.create_table(
        'project_metrics',
        sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('metric_key', sa.String(length=80), nullable=False),
        sa.Column('metric_value', sa.String(length=500), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column(
            'id',
            sa.UUID(as_uuid=False),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
            name=op.f('fk_project_metrics_project_id_projects'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_project_metrics')),
        sa.UniqueConstraint('project_id', 'metric_key', name='project_metric'),
    )
    op.create_table(
        'project_niches',
        sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_project_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
            name=op.f('fk_project_niches_project_id_projects'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'project_id', 'niche_id', name=op.f('pk_project_niches')
        ),
    )
    op.create_table(
        'project_tech_tags',
        sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('tech_tag_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
            name=op.f('fk_project_tech_tags_project_id_projects'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['tech_tag_id'],
            ['tech_tags.id'],
            name=op.f('fk_project_tech_tags_tech_tag_id_tech_tags'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'project_id', 'tech_tag_id', name=op.f('pk_project_tech_tags')
        ),
    )
    op.create_table(
        'publication_niches',
        sa.Column('publication_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_publication_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['publication_id'],
            ['publications.id'],
            name=op.f('fk_publication_niches_publication_id_publications'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'publication_id', 'niche_id', name=op.f('pk_publication_niches')
        ),
    )
    op.create_table(
        'reference_niches',
        sa.Column('reference_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_reference_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['reference_id'],
            ['references.id'],
            name=op.f('fk_reference_niches_reference_id_references'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'reference_id', 'niche_id', name=op.f('pk_reference_niches')
        ),
    )
    op.create_table(
        'skill_category_niches',
        sa.Column('skill_category_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('niche_id', sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ['niche_id'],
            ['niches.id'],
            name=op.f('fk_skill_category_niches_niche_id_niches'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['skill_category_id'],
            ['skill_categories.id'],
            name=op.f(
                'fk_skill_category_niches_skill_category_id_skill_categories'
            ),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'skill_category_id',
            'niche_id',
            name=op.f('pk_skill_category_niches'),
        ),
    )
    op.create_table(
        'skill_category_skills',
        sa.Column('skill_category_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['skill_category_id'],
            ['skill_categories.id'],
            name=op.f(
                'fk_skill_category_skills_skill_category_id_skill_categories'
            ),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skills.id'],
            name=op.f('fk_skill_category_skills_skill_id_skills'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'skill_category_id',
            'skill_id',
            name=op.f('pk_skill_category_skills'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_category_skills')
    op.drop_table('skill_category_niches')
    op.drop_table('reference_niches')
    op.drop_table('publication_niches')
    op.drop_table('project_tech_tags')
    op.drop_table('project_niches')
    op.drop_table('project_metrics')
    op.drop_table('project_case_studies')
    op.drop_table('profile_stats')
    op.drop_table('niche_priorities')
    op.drop_table('language_niches')
    op.drop_table('experience_skills')
    op.drop_table('experience_niches')
    op.drop_table('experience_bullets')
    op.drop_table('education_niches')
    op.drop_table('certificate_niches')
    op.drop_table('award_niches')
    op.drop_table('translations')
    op.drop_table('tech_tags')
    op.drop_table('skills')
    op.drop_table('skill_categories')
    op.drop_table('references')
    op.drop_table('publications')
    op.drop_table('projects')
    op.drop_table('profile')
    op.drop_table('niches')
    op.drop_table('languages')
    op.drop_table('experiences')
    op.drop_table('education')
    op.drop_table('certificates')
    op.drop_table('awards')
    # ### end Alembic commands ###
    # Los tipos ENUM nativos NO se borran con DROP TABLE — Alembic no los
    # autogenera en el downgrade. Sin esto, un re-upgrade falla con
    # "type already exists". Se borran al final, ya sin tablas que los usen.
    for enum_name in (
        'locale',
        'seniority',
        'project_type',
        'project_status',
        'skill_kind',
        'bullet_kind',
        'entity_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
