name: Astro Studio

env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
  ASTRO_DB_URL: ${{ secrets.ASTRO_DB_URL }}
  ASTRO_DB_TOKEN: ${{ secrets.ASTRO_DB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bypablo
          chmod 600 ~/.ssh/bypablo

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.1

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9.3.0
          run_install: true

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run merge build
        env:
          ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
          ASTRO_DB_URL: ${{ secrets.ASTRO_DB_URL }}
          ASTRO_DB_TOKEN: ${{ secrets.ASTRO_DB_TOKEN }}
        run: |
          source $GITHUB_ENV
          pnpm run start:dev mergeBuild

      - name: Notify Astro Studio
        uses: withastro/action-studio@main
        with:
          token: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
